import assert from 'node:assert/strict';
const u=process.env.TEST_URL||'http://localhost:4173';
const post=(body,origin=u)=>fetch(u+'/api/session',{method:'POST',headers:{origin,'Content-Type':'application/x-www-form-urlencoded'},body,redirect:'manual'});
const html=await (await fetch(u)).text();
assert(html.includes('Entry code'));
assert(!html.includes('Your daily rhythm'));
assert(!(await post('code=wrong')).headers.has('set-cookie'));
assert.equal((await post('code='+encodeURIComponent(process.env.TEST_CODE||''),'https://invalid.example')).status,403);
const login=await post('code='+encodeURIComponent(process.env.TEST_CODE||''));
const cookie=login.headers.get('set-cookie');
assert(cookie,'Valid login must set a session cookie');
assert(cookie.includes('HttpOnly'));
assert((await (await fetch(u,{headers:{cookie:cookie.split(';')[0]}})).text()).includes('Your daily rhythm'));
assert((await (await fetch(u,{headers:{cookie:'practice_session=tampered'}})).text()).includes('Entry code'));
assert((await post('logout=yes')).headers.get('set-cookie').includes('Max-Age=0'));
console.log('PASS: gate, wrong code, origin, login, tampered session, logout');
