'use client';
import {useEffect,useState} from 'react';
import {Music2,Sun,Play,Pause,RotateCcw,Sprout} from 'lucide-react';
import {Button,Checkbox} from './controls';

const exercises=[
 {title:'Easy breathing, without a target',category:'Prepare',seconds:60,dose:'3 ordinary breaths. No holds or maximum inhale.',rest:'Pause naturally between breaths.',steps:['Choose a supported position that feels comfortable. Do not force a tall chest or pull your shoulders back.','Let an ordinary breath come in through whichever route is comfortable. Let it leave without squeezing your abdomen.','Keep your jaw loose without deliberately stretching it. Stop trying to control the breath if it increases air hunger.'],example:'A quiet breath before an ordinary sentence, not a breath before a race.',stop:'Skip breath practice if breathing is uncomfortable at rest. Do not use it to push through breathing difficulty.',voice:false},
 {title:'Gentle lip trill',category:'Voice',seconds:60,dose:'Optional starting trial: 3 repetitions of 2 to 3 seconds.',rest:'10 to 15 seconds of quiet rest after each repetition.',steps:['Only try this when breathing, normal speech and jaw movement are comfortable, and your voice is not hoarse or tired.','Let the lips meet loosely. On a small, easy exhale, allow a soft brrr on one comfortable speaking-range pitch.','Keep volume quiet and the pitch steady. If the lips will not flutter easily, skip it; do not blow harder, press your cheeks or clench your jaw.'],example:'A soft voiced brrr, briefly. No long breath, siren or range challenge.',stop:'Stop with throat pressure, jaw effort, dizziness, breathlessness or a rougher voice. A lip trill is optional, not a test you must pass.',voice:true},
 {title:'Easy humming',category:'Voice',seconds:60,dose:'Alternative to the trill: 3 repetitions of 2 to 3 seconds.',rest:'10 to 15 seconds between sounds.',steps:['Use this instead of the trill, not as another set to accumulate.','With lips lightly together and teeth not clenched, make a small comfortable mmm at speaking pitch.','Let the sound end before you need to push out air. Do not chase vibration in your face or force sound through a blocked nose.'],example:'A quiet mmm of agreement. Keep it easy, short and unforced.',stop:'Skip if nasal blockage makes this uncomfortable, or if it increases jaw effort, pressure, strain or hoarseness.',voice:true},
 {title:'Hear the pitch before singing',category:'Music',seconds:120,dose:'Choose 3 comfortable notes on a keyboard; listen twice to each.',rest:'A few quiet seconds between notes.',steps:['Play a note on your own instrument or a reference recording.','Listen to its start and ending. Imagine matching it without making sound.','Play the next note and decide whether it is higher or lower. This drill stays non-vocal.'],example:'Play three nearby notes in a rising pattern, then reverse them.',stop:'Keep playback at a comfortable volume. This is ear training, not a hearing or medical test.',voice:false},
 {title:'Rhythm without vocal load',category:'Music',seconds:120,dose:'One short rhythm, 3 repetitions.',rest:'15 seconds between repetitions.',steps:['Choose a short phrase from your own song.','Tap its syllable rhythm gently with one finger; keep shoulders and jaw comfortable.','Repeat once slower, then once at the original pace. No singing, whispering or breath holding.'],example:'Tap the rhythm of “Let the morning in.” Change which syllable gets emphasis.',stop:'Stop tapping if it creates tension or pain. You can simply listen instead.',voice:false},
 {title:'Mark the phrase',category:'Music',seconds:120,dose:'One lyric line; mark 1 comfortable phrase boundary.',rest:'Read silently between attempts.',steps:['Write a short line from your own lyrics.','Put a slash where the musical idea can pause. Do not try to fit an entire long line into one breath.','Listen to the melody and move the slash if the meaning becomes clearer. Keep this exercise silent.'],example:'Let the morning in / let the day begin.',stop:'No breath-duration competition. Written phrasing does not require a physical breath drill.',voice:false},
 {title:'One easy sung phrase',category:'Voice',seconds:60,dose:'Optional alternative: one short phrase, at most 3 attempts.',rest:'At least 15 seconds, and longer than the phrase itself.',steps:['Choose this instead of another voiced exercise for the first trial. Readiness checks must be comfortable.','Use your own short lyric in an easy middle range at conversational volume. Stop before the breath feels depleted.','Keep your expression natural. Do not force a smile, widen your jaw, lift your chin or push for a brighter sound.'],example:'Sing just “Let the morning in” on a comfortable melody. No belting or high-note testing.',stop:'Stop immediately if speech or singing becomes harder, rougher, painful or breathless.',voice:true},
 {title:'Quiet recovery',category:'Rest',seconds:120,dose:'2 minutes without deliberate voicing.',rest:'This is the rest, not another exercise.',steps:['Let your voice rest. Do not whisper to test it.','Notice whether you feel the same as before the trial; there is no need to keep checking your face in a mirror.','If you feel worse later or the next morning, skip further voiced trials rather than repeating them to fix the sensation.'],example:'Quiet listening or silence, with no extra warm-down sounds.',stop:'Persistent breathing, jaw or voice difficulty needs a focused assessment before increasing vocal load.',voice:false}
];

export default function Calendar(){
 const [selected,setSelected]=useState(0),[ready,setReady]=useState([false,false,false,false]),[remaining,setRemaining]=useState(60),[running,setRunning]=useState(false);
 const exercise=exercises[selected],canVoice=ready.every(Boolean),blocked=exercise.voice&&!canVoice;
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setRemaining(n=>Math.max(0,n-1)),1000);return()=>clearInterval(id);},[running]);
 function choose(index:number){setSelected(index);setRemaining(exercises[index].seconds);setRunning(false);if(window.matchMedia('(max-width:760px)').matches)document.querySelector('.practice')?.scrollIntoView({block:'start'});}
 return <><header><strong><Sun size={20}/> Singing Practice</strong><span><Sprout size={15}/> XIV / HEALTH</span></header><div className="garden-band" role="img" aria-label="Sunlit solarpunk conservatory with lush plants and solar architecture"/>
 <main className="workspace"><section className="heading"><div><p className="eyebrow"><Sprout size={14}/> VOICE / BREATH / MUSICIANSHIP</p><h1>Practice your voice.</h1><p>Exercises, examples and rest. No work blocks, meal schedule or completion score.</p></div></section>
 <section className="readiness"><h2>Before trying a voiced exercise</h2>{['Breathing is comfortable at rest','Normal speech is comfortable','Jaw moves comfortably, without locking','Voice is not hoarse or tired'].map((label,i)=><label key={label}><Checkbox checked={ready[i]} onCheckedChange={value=>{setReady(old=>old.map((v,j)=>i===j?value:v));setRunning(false);}}/>{label}</label>)}<p>{canVoice?'Choose one gentle voiced trial, not every exercise. These checks are not medical clearance.':'Use the non-vocal exercises today if any of these are not true.'}</p></section>
 <p className="session-rule"><strong>Starting dose, not a training target:</strong> choose a trill, a hum OR one phrase. Start with the brief trial below, not repeated rounds. No automatic progression, even if you are aerobically fit. These suggested doses are conservative examples, not a personalized therapy prescription.</p>
 <div className="columns"><section className="timeline"><h2>Exercise library <small>Choose a focus</small></h2>{exercises.map((item,i)=><article key={item.title} className={'row '+(selected===i?'selected':'')}><span className="exercise-number">{String(i+1).padStart(2,'0')}</span><button className="block" onClick={()=>choose(i)} aria-pressed={selected===i}><span className={'tag '+item.category}>{item.category}{item.voice?' / optional trial':''}</span><strong>{item.title}</strong><small>{item.dose}</small></button></article>)}</section>
 <aside><section className="practice"><p className="eyebrow">{exercise.category} / {String(selected+1).padStart(2,'0')}</p><Music2 size={30}/><h2>{exercise.title}</h2>{blocked&&<p className="voice-hold" role="status">Read the example, but skip voicing while any readiness check is unmet. Choose pitch listening, rhythm or written phrasing instead.</p>}<p className="dose">{exercise.dose}<br/><strong>Rest:</strong> {exercise.rest}</p><ol className="exercise-steps">{exercise.steps.map(step=><li key={step}>{step}</li>)}</ol><p className="exercise-example"><strong>Example</strong><br/>{exercise.example}</p><p className="exercise-stop"><strong>Stop / skip</strong><br/>{exercise.stop}</p><div className="timer">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</div><small>Session timer includes rests. It is not a sound-hold timer.</small><div className="actions"><Button onClick={()=>setRunning(!running)} disabled={blocked||remaining===0} aria-label={running&&remaining>0?'Pause timer':'Start timer'} title={running&&remaining>0?'Pause timer':'Start timer'}>{running&&remaining>0?<Pause/>:<Play/>}</Button><Button variant="outline" onClick={()=>{setRunning(false);setRemaining(exercise.seconds);}} aria-label="Reset timer" title="Reset timer"><RotateCcw/></Button></div></section>
 <section className="guardrails"><h2>Training without forcing</h2><p>Lip trills and humming are voice-training techniques, not a diagnosis or a fix for a displaced jaw, nerve problem or restricted breathing. Endurance fitness does not tell us how much vocal load is appropriate.</p><p>No neck loading, jaw manipulation, chest pressure, breath holds or singing through strain. Persistent breathing, speech or jaw problems need assessment before harder voice training. New severe breathing difficulty, chest pain or fainting needs urgent care.</p><a href="https://www.asha.org/practice-portal/clinical-topics/voice-disorders/">Voice exercises / ASHA</a><br/><a href="https://www.nidcd.nih.gov/health/taking-care-your-voice">Voice care / NIDCD</a></section></aside></div></main><footer><Sprout size={16}/>Make the sound easier, not louder.</footer></>;
}
