using System.Collections.Generic;

namespace GateKPT.MusicOS.Services;

public static class AudioProcessingPresetCatalog
{
    public static IReadOnlyList<AudioProcessingPreset> Defaults { get; } =
    [
        new(
            "Late Night Chrome",
            "late-night-chrome",
            90,
            -13,
            "Primary Tory lane: glossy melodic R&B/rap lead, compressed, intimate, bright, and slightly synthetic.",
            LowPassHz: 15500,
            BassDb: -1.0,
            TrebleDb: 2.4,
            CompressorThresholdDb: -22.0,
            CompressorRatio: 3.5,
            MakeupGainDb: 3.0,
            DelayMs: 92,
            DelayDecay: 0.18,
            StereoWidth: 1.25),
        new(
            "Silk Synth",
            "silk-synth",
            110,
            -13,
            "Lil Tecca HVN ON EARTH color: smoother hook vocal that sits like a synth lead.",
            LowPassHz: 13500,
            BassDb: -2.0,
            TrebleDb: 3.2,
            CompressorThresholdDb: -24.0,
            CompressorRatio: 4.0,
            MakeupGainDb: 3.5,
            DelayMs: 118,
            DelayDecay: 0.22,
            Chorus: true,
            StereoWidth: 1.55),
        new(
            "Luna Pop",
            "luna-pop",
            85,
            -14,
            "Rauw color: airy Spanish/English pop vocal, warm presence, light rhythmic delay.",
            LowPassHz: 16000,
            BassDb: 0.5,
            TrebleDb: 2.0,
            CompressorThresholdDb: -20.0,
            CompressorRatio: 2.8,
            MakeupGainDb: 2.5,
            DelayMs: 145,
            DelayDecay: 0.16,
            StereoWidth: 1.18),
        new(
            "Cloud Doubles",
            "cloud-doubles",
            120,
            -16,
            "Wide tuned-style background doubles and adlibs. Softer, wider, more washed than the lead.",
            LowPassHz: 12500,
            BassDb: -3.0,
            TrebleDb: 2.8,
            CompressorThresholdDb: -24.0,
            CompressorRatio: 3.2,
            MakeupGainDb: 1.5,
            DelayMs: 175,
            DelayDecay: 0.28,
            Chorus: true,
            StereoWidth: 1.75),
        new(
            "Raw Clean",
            "raw-clean",
            80,
            -14,
            "Basic cleaned vocal before style decisions: rumble cleanup, steady level, no extra sauce.",
            LowPassHz: 18000,
            CompressorThresholdDb: -18.0,
            CompressorRatio: 2.2,
            MakeupGainDb: 1.5),
        new("No processing", "dry", 0, 0, "Sync only. Leave tonal and loudness processing untouched."),
    ];
}

public sealed record AudioProcessingPreset(
    string Name,
    string Slug,
    int HighPassHz,
    int TargetLufs,
    string Description,
    int LowPassHz = 0,
    double BassDb = 0,
    double TrebleDb = 0,
    double CompressorThresholdDb = 0,
    double CompressorRatio = 0,
    double MakeupGainDb = 0,
    int DelayMs = 0,
    double DelayDecay = 0,
    bool Chorus = false,
    double StereoWidth = 1.0);
